version: '3.1'
services: 
  db:
    image: postgres:16.3
    container_name: some-postgres-dc
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - 5000:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
